# nginx proxy address - http://172.17.0.1:8097

name: amp
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  amp:
    image: mitchtalmadge/amp-dockerized:latest
    pull_policy: always
    container_name: amp-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - amp
    ports:
      - "172.17.0.1:8097:8080"
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./volumes/config/amp:/config
      - ./volumes/data/amp:/data

networks:
  amp:
    external: false
